In [1]:
x=5 
type(x) 

int

In [4]:
x=2
y=5
print("l'addition de x et y est",x+y)

l'addition de x et y est 7


In [6]:
ch= "Hello"
ch=ch+" word" 
print (ch) 

Hello word


In [7]:
for x in range(4):
    print(x)

0
1
2
3


In [8]:
for x in range(1, 4):
    print(x)

1
2
3


In [9]:
for x in range(2, 20, 3):
    print(x)

2
5
8
11
14
17


In [13]:
def my_function():
    print("Hello from a function")


In [14]:
my_function()

Hello from a function


In [27]:
import numpy as np
new_array=np.array([[1,2,3],[4,5,6]])
print(new_array.shape)
print (new_array[0,0],new_aaray[0,1],new_aaray[1,0],new_aaray[1,1])


(2, 3)
1 2 4 5


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [33]:
import numpy as np 
value=np.full(10,8)
print(value)

[8 8 8 8 8 8 8 8 8 8]


In [38]:
import numpy as np 
array=np.eye(10)
print(array)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [44]:
import numpy as np 
x=np.array([[1,2],[3,4]] ,dtype=np.float64)
print(x)
y=np.array([[5,6],[7,8]] ,dtype=np.float64)
print(y)
A=np.add(x,y)
print(A)
B=y-x
print(B)
c=np.subtract(x,y)
print(c)


[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]
[[4. 4.]
 [4. 4.]]
[[-4. -4.]
 [-4. -4.]]


In [50]:
import numpy as np 
x=np.array([[1,2],[3,4],[5,6]])
bool_idx=(x>2)
print(bool_idx)
print(x[bool_idx])
print (x[x>3])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[4 5 6]


In [51]:
import pandas as pd 
s=pd.Series(["al","DataScience","Web"])
print(s)


0             al
1    DataScience
2            Web
dtype: object


In [53]:
#pandas 
#l'avantage  par rapport aux tableaux NumPy est que nous pouvons créer une série en utilisant nos propres index
#ici par exemple fruits est l'index
import pandas as pd 
fruits=['apple','oranges','cherries','pears']
quantite=[20,33,52,10]
s=pd.Series(quantite, index=fruits)
print(s)

apple       20
oranges     33
cherries    52
pears       10
dtype: int64


In [3]:
#Dataframe from NumPy array
import numpy as np
import pandas as pd
my_numpy_array=np.random.randn(3,4)
df=pd.DataFrame(my_numpy_array, columns=list("abcd"))
print (my_numpy_array)
print(df)

[[-1.07045126  0.94217159 -0.69266264 -0.07591039]
 [ 0.51107685  0.0318613   0.78505722  2.56603494]
 [ 0.90304439  0.14328782  0.20700857 -1.5553374 ]]
          a         b         c         d
0 -1.070451  0.942172 -0.692663 -0.075910
1  0.511077  0.031861  0.785057  2.566035
2  0.903044  0.143288  0.207009 -1.555337


In [4]:
#From a dictionary
import numpy as np
import pandas as pd
cities={"name":["London","Berlin","madrid","Rome"]
        ,"population":[8615222,6546564,5646645,5847326],
        "country":["England","Germany","Spain","Italy"]}
city_frame=pd.DataFrame(cities)
city_frame

name  population  country
0  London     8615222  England
1  Berlin     6546564  Germany
2  madrid     5646645    Spain
3    Rome     5847326    Italy

In [5]:
import pandas as pd
dic1={"name":["London","Berlin","madrid","Rome"]
      , "last_name":["yasmine","bouazza","yassine","ikbel"] , 
      "age": [12,12,15,16]    
}
data=pd.DataFrame(dic1)
data.to_csv('Data.csv')
new_data=pd.read_csv('Data.csv')
new_data.head(4)


Unnamed: 0    name last_name  age
0           0  London   yasmine   12
1           1  Berlin   bouazza   12
2           2  madrid   yassine   15
3           3    Rome     ikbel   16

In [40]:
#pour afficher le la derniére ligne de la data
new_data.tail(1)
#pour le calcul statique pour une colonne spécifique 
new_data['age'].describe()
new_data['name'].describe()

count        4
unique       4
top       Rome
freq         1
Name: name, dtype: object

In [41]:
new_data.iloc[2:4,2:4]
new_data.iloc[1]


Unnamed: 0          1
name           Berlin
last_name     bouazza
age                12
Name: 1, dtype: object

In [9]:
#index
new_data
new_data
new_data[new_data["age"]>12]
new_data[new_data["name"]=="madrid"]

Unnamed: 0    name last_name  age
2           2  madrid   yassine   15

In [10]:
new_data["full_name"]=new_data["name"]+"  "+new_data["last_name"]
new_data.head()

Unnamed: 0    name last_name  age        full_name
0           0  London   yasmine   12  London  yasmine
1           1  Berlin   bouazza   12  Berlin  bouazza
2           2  madrid   yassine   15  madrid  yassine
3           3    Rome     ikbel   16      Rome  ikbel

In [11]:
#concatination 
dict2 ={
    "name": ["omar"] ,
    "last_name":["luca"] ,
    "age":[28] ,
    "full_name": ["omar luca"] 
}
data2=pd.DataFrame(dict2)
new_data=pd.concat([new_data,data2])
new_data

Unnamed: 0    name last_name  age        full_name
0         0.0  London   yasmine   12  London  yasmine
1         1.0  Berlin   bouazza   12  Berlin  bouazza
2         2.0  madrid   yassine   15  madrid  yassine
3         3.0    Rome     ikbel   16      Rome  ikbel
0         NaN    omar      luca   28        omar luca

In [32]:
for x in range(2000, 3200+1):
 if x%7==0: 
  print(x)

2002
2009
2016
2023
2030
2037
2044
2051
2058
2065
2072
2079
2086
2093
2100
2107
2114
2121
2128
2135
2142
2149
2156
2163
2170
2177
2184
2191
2198
2205
2212
2219
2226
2233
2240
2247
2254
2261
2268
2275
2282
2289
2296
2303
2310
2317
2324
2331
2338
2345
2352
2359
2366
2373
2380
2387
2394
2401
2408
2415
2422
2429
2436
2443
2450
2457
2464
2471
2478
2485
2492
2499
2506
2513
2520
2527
2534
2541
2548
2555
2562
2569
2576
2583
2590
2597
2604
2611
2618
2625
2632
2639
2646
2653
2660
2667
2674
2681
2688
2695
2702
2709
2716
2723
2730
2737
2744
2751
2758
2765
2772
2779
2786
2793
2800
2807
2814
2821
2828
2835
2842
2849
2856
2863
2870
2877
2884
2891
2898
2905
2912
2919
2926
2933
2940
2947
2954
2961
2968
2975
2982
2989
2996
3003
3010
3017
3024
3031
3038
3045
3052
3059
3066
3073
3080
3087
3094
3101
3108
3115
3122
3129
3136
3143
3150
3157
3164
3171
3178
3185
3192
3199
